# Generated by Django 5.0.2 on 2024-02-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateTimeField()),
                ('avatar', models.FileField(upload_to='_my')),
                ('number_phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('telegram_link', models.CharField(max_length=20)),
                ('vk_link', models.CharField(max_length=20)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.TextField(max_length=255)),
                ('education', models.TextField(max_length=255)),
                ('experience', models.TextField(max_length=255)),
                ('courses', models.TextField(max_length=255)),
                ('resume_pdf', models.FileField(upload_to='_my')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
