# Generated by Django 5.0.2 on 2024-02-26 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalvaultapp', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_html',
            field=models.FileField(upload_to='_my/resume/html/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html'])]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_pdf',
            field=models.FileField(upload_to='_my/resume/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
