# Generated by Django 5.0.2 on 2024-02-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalvaultapp', '0002_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
    ]
