# Generated by Django 5.0.2 on 2024-02-21 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('type_project', models.CharField(max_length=50)),
                ('stack', models.CharField(max_length=255)),
                ('full_descrtiption', models.FileField(upload_to='_projects/')),
                ('main_image', models.FileField(upload_to='_project/images/main/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_image', models.CharField(max_length=10, null=True)),
                ('image', models.FileField(upload_to='_project/images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.project')),
            ],
        ),
    ]
