# Generated by Django 5.0.2 on 2024-02-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='full_descrtiption',
            new_name='full_description',
        ),
    ]
