# Generated by Django 5.0.2 on 2024-02-26 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0004_alter_project_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.FileField(upload_to='_project/images/main/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.FileField(upload_to='_project/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
        ),
    ]
